---
title: "Coverage Probability"
output: html_document
---

### Donald Kane
### November 29, 2021

```{r message=FALSE, warning=FALSE}
require(stats4)
library(tidyverse)
library(dplyr)
library(ggplot2)
```


# Introduction



# Generate a Sample of Size N From a Known Distribution

```{r}
N <- 201 # parameters

generate_data <- function(N){ 
  # Hard coded standard normal distribution
  rnorm(N) 
}
data <- generate_data(N)
```

# Estimate Distribution using Maximum Likelihood Estimation

```{r}
nLL <- function(mean, sd){
  fs <- dnorm(
        data
      , mean = mean
      , sd = sd
      , log = TRUE
    ) 
  -sum(fs)
}

fit <- mle(
    nLL
  , start = list(mean = 0, sd = 1)
  , method = "L-BFGS-B"
  , lower = c(0, 0.01)
)

mu_hat <- coef(fit)[[1]]
mu_hat
sigma_hat <- coef(fit)[[2]]
sigma_hat

hist(
  data,
  freq = FALSE,
  main = "Distribution of Sample Data, N = 201",
  breaks = 25
)
curve(
  dnorm(
    x,
    mu_hat,
    sigma_hat),
  lw = 3,
  col = "red",
  add = TRUE
  )
```


# Approximate the Sampling Distribution of the Median

```{r}
meds <- NA
for (i in 1:N){
  samples <- rnorm(
    N, 
    mean = mu_hat,
    sd = sigma_hat)
  meds[i] <- median(samples)
}
mean(meds)

hist(meds, breaks = 50, main = "Distribution of \nEstimated Medians", xlab = "Estimated Medians")
abline(v = mean(meds), lwd = 3, col = "red")
```

# 95% confidence interval

```{r}
boot_ci <- function(data, summary = "median"){
  # Hard coded number of draws
  R <- 5000
  # Set median as default summary measure
  sm <- get(summary)
  sampdist <- rep(NA, R)
  for(i in 1:R){
    b <- sample(data, length(data), replace = TRUE)
    sampdist[i] <- sm(b)
  }
  # Hard coded symmetric density interval
  quantile(sampdist, c(0.025, 0.975))
}
conf <- boot_ci(data)
conf
```

# Concept of Coverage Probability

```{r}
capture_median <- function(ci){
  # Hard coded 0 as parameter of interest
  1*(ci[1] < 0 & 0 < ci[2])
}
M <- 50 # Make small, we are still testing the code
captures <- rep(NA, M)
for(i in 1:M){
  captures[i] <- 
    201 %>% generate_data %>% boot_ci %>% capture_median
}
capture_prob <- mean(captures)
capture_prob
```



# Possible Changes




