---
title: "Log Transformation"
output: html_document
---

### Donald Kane
### October 11, 2021

# Introduction

```{r message=FALSE}
library(ggplot2)
library(dplyr)
```


# Gamma Distribution Probability Density Function
```{r}
x <- seq(0,10, by = 0.1)
g_PDF <- dgamma(x, shape = 3, scale = 1)
df <- data.frame(x, g_PDF, g_CDF)

ggplot(df, aes(x = x)) +
        geom_line(y = g_PDF) +
        geom_vline(aes(xintercept = mean(rgamma(1000, shape = 3, 
                                                scale = 1)),
                   color = "mean")) +
        geom_vline(aes(xintercept = qgamma(0.5, shape = 3, scale = 1),
                   color = "median")) +
        theme_classic() +
        ylim(0,0.5) +
        labs(
                title = "Gamma Distribution PDF",
                x = "x",
                y = "x ~ Gamma(shape = 3, scale = 1)"
        ) +
        scale_color_manual(name = "Statistics", 
                           values = c(median = "green", mean = "red"))
```

# Gamma Distribution Cummulative Density Function

```{r}
x <- seq(0,10, by = 0.1)
g_CDF <- pgamma(x, shape = 3, scale = 1)
ggplot(df, aes(x = x)) +
        geom_line(y = g_CDF) +
        geom_vline(aes(xintercept = mean(rgamma(1000, shape = 3, 
                                                scale = 1)),
                   color = "mean")) +
        geom_vline(aes(xintercept = qgamma(0.5, shape = 3, scale = 1),
                   color = "median")) +
        theme_classic() +
        ylim(0,1) +
        labs(
                title = "Gamma Distribution CDF",
                x = "x",
                y = "x ~ Gamma(shape = 3, scale = 1)"
        ) +
        scale_color_manual(name = "Statistics", 
                           values = c(median = "green", mean = "red"))
```

# Gamma Log Distribution Probability Density Function

```{r}
g_log <- log(rgamma(1000, shape = 3, scale = 1))

plot(density(g_log), type = "l", 
     main = "Log Gamma Probability Density Function")
abline(v = mean(g_log), col= 'red')
abline(v = median(g_log), col = "green")
legend('topleft', c('mean', 'median'),
       col = c('red', 'green'), lty = c(1, 1))
```

# Gamma Log Distribution Cummulative Density Function

```{r}
g_log <- log(rgamma(1000, shape = 3, scale = 1))

plot(ecdf(g_log), main = "Log Gamma Cummulative Density Function")
abline(v = mean(g_log), col= 'red')
abline(v = median(g_log), col = "green")
legend('bottomright', c('mean', 'median'),
       col = c('red', 'green'), lty = c(1, 1))

```

# Geometric and Arithmetic Means

```{r}
geometric = rep(NA, 1000)
arithmetic = rep(NA, 1000)
difference = rep(NA, 1000)

for (i in 1:1000){
  q = rgamma(100, shape = 3, scale = 1)
  
  arithmetic[i] = mean(q)
  geometric[i] = exp(mean(log(q)))
  difference[i] = abs(arithmetic[i] - geometric[i])
}

means = data.frame(arithmetic, geometric, difference)

# scatter plot
ggplot(means, aes(x = geometric, y = arithmetic))+
  geom_point()+
  labs(x = 'Geometric Means',
       y = 'Arithmetic Means',
       title = 'Geometric vs. Arithmetic Means')

ggplot(means, aes(x = dif))+
  geom_histogram()+
  labs(x = 'Difference',
       y = 'Frequency',
       title = 'Differences between Means')
```


# Log Normal Distribution



```{r message=FALSE, warning=FALSE}
x1 <- seq(0,10, by = 0.1)
ln_PDF <- dlnorm(x1, meanlog = -1, sdlog = 1)
ln_CDF <- plnorm(x1, meanlog = -1, sdlog = 1)

df1 <- data.frame(x1, ln_PDF, ln_CDF)

ggplot(df1, aes(x = x1)) +
        geom_line(y = ln_PDF) +
        geom_vline(aes(xintercept = mean(rlnorm(1000, 
                                                meanlog = -1, sdlog = 1)),
                   color = "mean")) +
        geom_vline(aes(xintercept = qlnorm(0.5, meanlog = -1, sdlog = 1),
                   color = "median")) +
        theme_bw() +
        labs(
                title = "Log Normal Distribution PDF \nMean = -1, Standard Deviation = 1",
                x = "x",
                y = "x ~ Log Normal"
        ) +
        ylim(0,2)
        scale_color_manual(name = "Statistics", 
                           values = c(median = "green", mean = "red"))

ggplot(df1, aes(x = x1)) +
        geom_line(y = ln_CDF) +
        geom_vline(aes(xintercept = mean(rlnorm(1000, 
                                                meanlog = -1, sdlog = 1)),
                   color = "mean")) +
        geom_vline(aes(xintercept = qlnorm(0.5, meanlog = -1, sdlog = 1),
                   color = "median")) +
        theme_bw() +
        labs(
                title = "Log Normal Distribution CDF \nMean = -1, Standard Deviation = 1",
                x = "x",
                y = "x ~ Log Normal"
        ) +
        ylim(0,1) +
        scale_color_manual(name = "Statistics", 
                           values = c(median = "green", mean = "red"))
```

### Uniform Distribution

```{r}
x2 <- seq(-1,13, by = 0.1)
u_PDF <- dunif(x2, min = 0, max = 12)
u_CDF <- punif(x2, min = 0, max = 12)
u_log_PDF <- log(dunif(x2, min = 0, max = 12))
u_log_CDF <- log(punif(x2, min = 0, max = 12))

df2 <- data.frame(x2, u_PDF, u_CDF, u_log_PDF, u_log_CDF)

ggplot(df2, aes(x = x2)) +
        geom_line(y = u_PDF) +
        geom_vline(aes(xintercept = mean(runif(1000, 0, 12)),
                   color = "mean")) +
        geom_vline(aes(xintercept = qunif(0.5, 0, 12),
                   color = "median")) +
        theme_bw() +
        labs(
                title = "Uniform Distribution PDF",
                x = "x",
                y = "x ~ Uniform(0, 12)"
        ) +
        ylim(0,1) +
        scale_color_manual(name = "Statistics", 
                           values = c(median = "green", mean = "red"))

ggplot(df2, aes(x = x2)) +
        geom_line(y = u_CDF) +
        geom_vline(aes(xintercept = mean(runif(1000, 0, 12)),
                   color = "mean")) +
        geom_vline(aes(xintercept = qunif(0.5, 0, 12),
                   color = "median")) +
        theme_bw() +
        labs(
                title = "Uniform Distribution CDF",
                x = "x",
                y = "x ~ Uniform(0,12)"
        ) +
        ylim(0,1) +
        scale_color_manual(name = "Statistics", 
                           values = c(median = "green", mean = "red"))

```


# Part 2










